# numpy ndarray 개요
- ndarray : n-dimentinal array(n차원 배열)

In [2]:
import numpy as np

In [8]:
lt = [1, 2, 3]
print('lt 타입 >>', type(lt))

ar = np.array(lt)
print('ar 타입 >>', type(ar))

print('ar.shape >>', ar.shape)
print('ar.shape 타입 >>', type(ar.shape))

lt 타입 >> <class 'list'>
ar 타입 >> <class 'numpy.ndarray'>
ar.shape >> (3,)
ar.shape 타입 >> <class 'tuple'>


In [12]:
ar2 = np.array([
    [1, 2, 3],
    [2, 3, 4], 
])

print('ar2 타입 >>', type(ar2))
print('ar2.shape >>', ar2.shape)
print('ar2.shape >>', type(ar2.shape))
ar2

ar2 타입 >> <class 'numpy.ndarray'>
ar2.shape >> (2, 3)
ar2.shape >> <class 'tuple'>


array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
ar3 = np.array([
    [1, 2, 3]
])

print('ar3 타입 >>', type(ar3))
print('ar3.shape >>', ar3.shape)
print('ar3.shape >>', type(ar3.shape))
ar3

ar3 타입 >> <class 'numpy.ndarray'>
ar3.shape >> (1, 3)
ar3.shape >> <class 'tuple'>


array([[1, 2, 3]])

In [14]:
ar.ndim

1

In [16]:
f'ar : {ar.ndim}차원, ar2 : {ar2.ndim}차원, ar3 : {ar3.ndim}차원'

'ar : 1차원, ar2 : 2차원, ar3 : 2차원'

# ndarray 데이터 타입

In [20]:
ar = np.array([1, 2, 3, 2.5])
print('ar type >>', type(ar))
print('ar dtype >>', ar.dtype)
print('ar shape >>', ar.shape)
ar

ar type >> <class 'numpy.ndarray'>
ar dtype >> float64
ar shape >> (4,)


array([1. , 2. , 3. , 2.5])

In [21]:
ar2 = np.array([1, 2, 'test'])
ar2

array(['1', '2', 'test'], dtype='<U11')

In [34]:
# 타입 변경 : int -> float
ar_int = np.array([1, 2, 3])
print('ar_int >>', ar_int)
print('ar_int type >>', ar_int.dtype, end='\n\n')

ar_float = ar_int.astype(float)
print('ar_float >>', ar_float)
print('ar_float type >>', ar_float.dtype)

ar_int >> [1 2 3]
ar_int type >> int32

ar_float >> [1. 2. 3.]
ar_float type >> float64


In [35]:
ar_float2 = np.array([1.1, 2.5, 3.8])
ar_float2.astype(int)

array([1, 2, 3])

# ndarray를 편하게 생성 - arange, zeros, ones
- range : 지정한 범위의 배열
- zeros : 모든 요소가 0인 배열
- ones : 모든 요소가 1인 배열

In [39]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [40]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [41]:
sequence_ar1 = np.arange(10)
print('sequence_ar1 >>', sequence_ar1)
print('sequence_ar1 type >>', type(sequence_ar1))
print('sequence_ar1 dtype >>', sequence_ar1.dtype)
print('sequence_ar1 shape >>', sequence_ar1.shape)

sequence_ar1 >> [0 1 2 3 4 5 6 7 8 9]
sequence_ar1 type >> <class 'numpy.ndarray'>
sequence_ar1 dtype >> int32
sequence_ar1 shape >> (10,)


In [46]:
# 모든 요소가 0인 ndarray 생성
# shape : (3, 2)
# dtype : int32
zero_ar = np.zeros((3,2))
zero_ar.dtype

dtype('float64')

In [47]:
zero_ar

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
zero_ar = np.zeros((3,2), dtype='int32')
zero_ar.dtype

dtype('int32')

In [49]:
zero_ar

array([[0, 0],
       [0, 0],
       [0, 0]])

In [50]:
zero_ar.shape

(3, 2)

In [54]:
# 모든 요소가 1인 ndarray 생성
# shape : (3, 2)
# dtype : float64
ones_ar = np.ones((3, 2))
print(ones_ar)
print('ones_ar dtype >>', ones_ar.dtype)
print('ones_ar shape >>', ones_ar.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
ones_ar dtype >> float64
ones_ar shape >> (3, 2)


# ndarray의 차원과 크기 변경 : reshape

In [56]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
ar.shape

(10,)

In [59]:
# 1차원 배열(10,) -> 2차원 배열(2, 5) 변환
ar2 = ar.reshape(2, 5)
ar2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
ar2.shape

(2, 5)

In [62]:
ar.reshape(2, 4) # 차원을 바꿀 때 배열의 크기를 맞춰 바꿔줘야 함

ValueError: cannot reshape array of size 10 into shape (2,)

In [64]:
## 2차원 배열(2, 5) -> 2차원 배열(5, 2)
ar3 = ar2.reshape(5,2)
print(ar3)
print(ar3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [69]:
# 자동으로 행 또는 열 설정
ar4 = ar.reshape(-1, 5)
ar4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
ar5 = ar.reshape(2, -1)
ar5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
# ar.reshape(4, -1) # 자동으로 행 또는 열을 설정할 수 없으면 에러

ValueError: cannot reshape array of size 10 into shape (4,newaxis)

In [73]:
ar = np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
# 1차원(8, 0) -> 3차원(2, 2, 2)
ar2 = ar.reshape(2, 2, 2)
ar2.shape
ar2.ndim
ar2.tolist()

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

In [83]:
# 3차원(2, 2, 2) -> 2차원(4, 2)
ar3 = ar2.reshape(4, 2)
ar3.shape

(4, 2)

In [89]:
# 3차원(2, 2, 2) -> 1차원(8, 0)
# ar4 = ar3.reshape(8,)
ar4 = ar2.reshape(-1,)
ar4

array([0, 1, 2, 3, 4, 5, 6, 7])

# ndarray의 요소 선택

In [90]:
ar = np.arange(start=1, stop=10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
ar.dtype

dtype('int32')

In [93]:
type(ar[2])

numpy.int32

In [95]:
# 마지막 요소 출력
ar[-1]

9

In [100]:
# 요소 변경
# 첫 번째 요수 1 -> 9
ar[0] = 9
ar

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [101]:
# 마지막 요소 : 9 -> 0
ar[-1] = 0 
ar

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [103]:
ar = np.arange(1, 10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
ar2 = ar.reshape(3, -1)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
ar2.shape

(3, 3)

In [107]:
# 요소(원소) 1을 추출
ar2[0][0]

1

In [108]:
ar2[0, 0] # numpy의 배열만 가능

1

In [109]:
# 요소(원소) 8을 추출
ar2[2,1]

8

- 슬라이싱

In [110]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
# 요소 1, 2, 3 추출
ar[:3]

array([1, 2, 3])

In [114]:
ar[:3].shape

(3,)

In [116]:
ar[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
ar2 = ar.reshape(-1, 3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
ar2[:2, :2] # 행과 열 슬라이싱 가능

array([[1, 2],
       [4, 5]])

In [167]:
ar2[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [134]:
ar2[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [168]:
ar2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
ar2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [174]:
ar2[:2, 0] # 슬라이싱과 인덱싱 혼합 가능


array([1, 4])

# 팬시 인덱싱(fancy indexing)
- 배열을 인덱스로 설정
- 배열의 요소: 정수(인덱스), 논리값(해당 인덱스를 출력할 지 논리값)
- 정수는 배열의 크기와 상관없지만 논리값은 배열의 크기와 맞춰야 함
- 정수(인덱스)는 같은 값을 여러 번 쓸 수 있음

In [176]:
ar = np.arange(1, 6)
ar

array([1, 2, 3, 4, 5])

- 홀수만 출력

In [178]:
ar[[0, 2, 4]]

array([1, 3, 5])

In [180]:
ar[[0, 0, 0, 2, 2, 4, 4, 4, 4]]

array([1, 1, 1, 3, 3, 5, 5, 5, 5])

In [182]:
# 불린 인덱싱(boolean indexing)
ar[[True, False, True, False, True]]

array([1, 3, 5])

In [186]:
# pandas의 마스크처럼 사용 가능
ar[(ar % 2)==1]

array([1, 3, 5])

In [194]:
ar2 = np.arange(1, 10).reshape(3, -1)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
ar2[[0, 0]]

array([[1, 2, 3],
       [1, 2, 3]])

In [207]:
# 0,0 2,2의 데이터 추출
ar2[[0, 2], [0, 2]]

array([1, 9])

In [208]:
# 0,0 2,0의 데이터 추출
ar2[[0, 2], 0]

array([1, 7])

In [210]:
# 0,1 ~ 0,2 2,1 ~ 2,2의 데이터 추출
ar2[[0, 2], 1:]

array([[2, 3],
       [8, 9]])

In [216]:
# 0,0 ~ 0,3 2,0 ~ 2,2까지 증가폭 2로 추출
ar2[[0, 2], ::2]

array([[1, 3],
       [7, 9]])

In [212]:
# 다차원 배열의 불린 인덱싱은 배열을 만들어 실행
idx = np.array(
    [[True, False, True], [False, False, True], [True, False, False]]
)

In [214]:
ar2[idx]

array([1, 3, 6, 7])