In [3]:
import numpy as np

# 요소 차이
- list : 숫자형, 문자열 등 모든 자료 타입을 가질 수 있음(여러 자료형 허용)
- array : 숫자형과 문자열이 혼합되면 모두 문자열로 변환(여러 자료형 불가)

In [4]:
lt = [1, 3, 'a', 'b']
ar = np.array([1, 3, 'a', 'b'])

In [5]:
lt

[1, 3, 'a', 'b']

In [6]:
ar

array(['1', '3', 'a', 'b'], dtype='<U11')

# 2차원 이상일 경우, 원소 개수
- list : 모든 요소의 길이가 달라도 가능
- array : 모든 요소의 길이가 같아야 함

In [8]:
lt = [[1], [3, 5], [7, 9, 10]]
# ar = np.array([[1], [3, 5], [7, 9, 10]]) # Error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [9]:
ar = np.array([[1, 3], [3, 5], [7, 9]])

In [10]:
lt

[[1], [3, 5], [7, 9, 10]]

In [11]:
ar

array([[1, 3],
       [3, 5],
       [7, 9]])

# 연산
- list 
    - + : 결합
    - -,/ : Error
    - * : 반복
- array  
    - 사칙연산 가능
    - 배열끼리 연산은 길이가 같아야 가능
    - 숫자형 데이터와 연산하면 모든 요소에 적용

In [12]:
lt_one = [1, 3, 5]
lt_two = [2, 4, 6]

# 덧셈
lt_one + lt_two

[1, 3, 5, 2, 4, 6]

In [14]:
# 뺄셈
# lt_one - lt_two #Error

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [15]:
# 곱셈
lt_one * 3

[1, 3, 5, 1, 3, 5, 1, 3, 5]

In [18]:
ar_one = np.array([1, 3, 5])
ar_two = np.array([2, 4, 6])

ar_one + ar_two

array([ 3,  7, 11])

In [17]:
# ar_one = np.array([1, 3, 5])
# ar_two = np.array([2, 4, 6, 8])

# ar_one + ar_two # 길이가 서로 다른 배열끼리 연산하면 Error

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [19]:
ar_one - ar_two

array([-1, -1, -1])

In [20]:
ar_one * ar_two

array([ 2, 12, 30])

In [21]:
ar_one / ar_two

array([0.5       , 0.75      , 0.83333333])

In [23]:
ar_one + 1

array([2, 4, 6])

In [24]:
ar_one - 10

array([-9, -7, -5])

In [22]:
ar_one * 2

array([ 2,  6, 10])

In [25]:
ar_one / 5

array([0.2, 0.6, 1. ])

# 연산 속도
- time.time()
    - 1970년 1월 1일 0시 0분 0초 이후 경과한 시간을 초단위로 반환
    - 정수부는 초단위이고, 소수부는 마이크로(micro) 초단위
    - 마이크로초(micro-second) : 백만 분의 1초

In [39]:
import time

# 리스트 연산 속도
lt = list(range(10 ** 8))

start = time.time()

for i in lt:
    lt[i] *= 2
    
end = time.time()

print(end - start)

9.610230207443237


In [40]:
# 배열 연산 속도
ar = np.array(range(10 ** 8))

start = time.time()

ar * 2
    
end = time.time()

print(end - start)

0.10402250289916992
